/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: a1d983f67f1abefdbdb931883ea0687d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
  }
  interface Env {
    LOADER: WorkerLoader;
  }
}
interface Env extends Cloudflare.Env {}
